/**
 *  Given two strings s and t which consist of only lowercase letters.
 *  String t is generated by random shuffling string s
 *  and then add one more letter at a random position.
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 */
public class _389_Find_the_Difference {
    public char findTheDifference(String s, String t) {
        int[] map = new int[256];
        for(int i = 0 ; i < s.length() ; i++)
        {
            char c = s.charAt(i);
            map[c - 'a'] += 1 ;
        }
        for(int j = 0 ; j < t.length() ; j++)
        {
            char c = t.charAt(j);
            map[c - 'a'] -= 1 ;
            if( map[c - 'a'] == -1 )
                return c;
        }
        return 'a';
    }
}
